---
sidebar: sidebar 
permalink: rn/whats_new.html 
keywords:  
summary:  
---
= Novità dell'API REST di Astra Control
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp aggiorna periodicamente l'API REST di Astra Control per offrire nuove funzionalità, miglioramenti e correzioni di bug.



== 5 agosto 2021 (21.08)

Questa release include l'introduzione di un nuovo modello di implementazione Astra e un'importante espansione dell'API REST.



=== Modello di implementazione di Astra Control Center

Oltre all'offerta di Astra Control Service esistente come servizio di cloud pubblico, questa release include anche il modello di implementazione on-premise di Astra Control Center. Puoi installare Astra Control Center presso la tua sede per gestire il tuo ambiente Kubernetes locale. I due modelli di implementazione di Astra Control condividono la stessa API REST, con piccole differenze indicate nella documentazione.



=== Espansione dei tipi DI risorse RIMANENTI

Il numero di risorse accessibili tramite l'API REST di Astra Control si è notevolmente ampliato, con molte delle nuove risorse che forniscono una base per l'offerta on-premise di Astra Control Center. Le nuove risorse includono: ASUP, diritto, funzionalità, licenza, impostazione, sottoscrizione, bucket, cloud, cluster, cluster gestito, back-end dello storage e classe di storage. Vedere link:../endpoints/resources.html["Risorse"] per ulteriori informazioni.



=== Endpoint aggiuntivi che supportano un'implementazione Astra

Oltre alle risorse REST estese, sono disponibili diversi altri nuovi endpoint API per supportare un'implementazione di Astra Control.

Supporto di OpenAPI:: Gli endpoint OpenAPI forniscono l'accesso al documento JSON OpenAPI corrente e ad altre risorse correlate.
Supporto di OpenMetrics:: Gli endpoint OpenMetrics forniscono l'accesso alle metriche degli account attraverso la risorsa OpenMetrics.




== 15 aprile 2021 (21.04)

Questa versione include le seguenti nuove funzioni e miglioramenti.



=== Introduzione dell'API REST

L'API REST di Astra Control è disponibile per l'utilizzo con l'offerta di Astra Control Service. È stato creato in base alle tecnologie REST e alle Best practice attuali. L'API fornisce le basi per l'automazione delle implementazioni Astra e include le seguenti funzionalità e vantaggi.

Risorse:: Sono disponibili quattordici tipi di risorse REST.
Accesso al token API:: L'accesso all'API REST viene fornito tramite un token di accesso API che è possibile generare nell'interfaccia utente web Astra. Il token API fornisce un accesso sicuro all'API.
Supporto per le raccolte:: Esiste un insieme completo di parametri di query che possono essere utilizzati per accedere alle raccolte di risorse. Alcune delle operazioni supportate includono il filtraggio, l'ordinamento e l'impaginazione.

